### ISSUE TITLE
Can I use it in Anki?

### ISSUE THREAD

**Issue by superpawko** [mbilbille/dmak#20]
I have read something in pull requests. I tried to use it in Anki,  but I failed. I don't know why. Could you tell me If your script is working in Anki?

**Comment by mbilbille** [comment]
Yes, I'd a similar request #19 to use Dmak within Anki.
What are you trying to do exactly, can you give me more insight ?

I'm not familiar with Anki, but as I said in https://github.com/mbilbille/dmak/pull/19#issuecomment-213720710 if you can run JS scripts within Anki it should work.

**Comment by superpawko** [comment]
I think the problem is with downloading SVG from website, when i use this code:

`<div id="draw"></div>
<script>
  var dmak = new Dmak('電車', {
    'element' : "draw"
  });
</script>`

Anki probably can't find files.  
I could make a new field in Anki DB to be a SVG file, import all SVG Anki files and then try to load it this way.  

var kanjiSVG= document.getElementById('kanjiSVG');

And draw this SVG using dmak somehow?

I know my post is chaos but I have zero experience with Javascript and I'm not Anki expert.

**Comment by mbilbille** [comment]
I would have recommended to load your SVG in JS via [kvg2js](https://github.com/mbilbille/kvg2js) but apparently this does not work either...
![2017-06-12_13-32-04](https://user-images.githubusercontent.com/718938/27032176-d415a556-4f73-11e7-9b65-cbcee210d998.png)

**Comment by mbilbille** [comment]
Close the issue for the month moment. Please reopen it if needed
