### ISSUE TITLE
404 when trying to load JS

### ISSUE THREAD

**Issue by sova** [mbilbille/dmak#21]
Is it necessary to have Dmak.js on a live server?  I am trying to run it on my dev box but I keep getting 404s.  Can I optionally host all the kanji svg on my box and teach Dmak the directory?  I think that would be faster that requesting the resources outside the home server.

**Comment by mbilbille** [comment]
This may help you https://github.com/mbilbille/dmak/pull/19#issuecomment-213720710

**Comment by sova** [comment]
Thanks!
