### ISSUE TITLE
click to redraw?

### ISSUE THREAD

**Issue by sova** [mbilbille/dmak#22]
hi.  pardon my lack of experience in javascript, how can i make it so that when a user clicks on the Dmak cell it redraws the kanji from 0?

**Comment by mbilbille** [comment]
Hello, the jquery plugin provides some helpers to erase/rewind and redraw the strokes, check that: https://github.com/mbilbille/dmak/blob/master/src/jquery.dmak.js#L25

And have a look to the demo website source code, can help: https://github.com/mbilbille/dmak/blob/gh-pages/js/website.dmak.js

**Comment by sova** [comment]
cool so just to make sure, grab the jQuery plugin, jQuery itself, and dmak will then let me invoke commands like .reset()?

**Comment by mbilbille** [comment]
Yes
